const HEADER_HEIGHT = 80
const HEADER_LOGO_HEIGHT = 30
const FOOTER_WHITE_SPACE_HEIGHT = 48
const DARK_MODE = 'dark-mode'

export {
  HEADER_HEIGHT,
  HEADER_LOGO_HEIGHT,
  FOOTER_WHITE_SPACE_HEIGHT,
  DARK_MODE,
}
